# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='username', max_length=100, unique=True)),
                ('nombre_completo', models.CharField(blank=True, default='Nombre', max_length=100)),
                ('numero_tel', models.CharField(max_length=50, null=True)),
                ('numero_cel', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('estatus', models.BooleanField(default=True, verbose_name='Cliente Activo?')),
                ('fechaintro', models.DateField(auto_now=True, null=True)),
                ('creditcard', models.CharField(blank=True, max_length=15, unique=True)),
                ('Empthy', models.CharField(blank=True, max_length=100, unique=True)),
                ('vacio', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
