# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
