# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160101_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Empthy',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
