# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160117_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Password',
            new_name='password',
        ),
    ]
