# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160117_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_pic',
            field=models.ImageField(null=True, upload_to='userpic/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
