# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='static/img/Products')),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField()),
                ('stock', models.DecimalField(decimal_places=0, max_digits=19)),
                ('vote', models.DecimalField(decimal_places=0, max_digits=1)),
                ('vacio1', models.CharField(max_length=200)),
                ('vacio2', models.CharField(max_length=200)),
                ('vacio3', models.CharField(max_length=200)),
            ],
        ),
    ]
